# Generated by Django 5.1.3 on 2024-12-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='review',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='character',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='character',
            name='share_publically',
        ),
        migrations.AddField(
            model_name='character',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
