# Generated by Django 5.1.3 on 2024-12-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='CharacterImage',
        ),
    ]
